version: '3'
services:
  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=sider
    ports:
      - 6379:6379
  static:
    build: ./data
    ports:
      - 4000:3000
    volumes:
      - ./data:/home/static
  solacher:
    depends_on:
      - redis
    build: ./solacher
    env_file: ./solacher/.env
    environment:
      - REDIS_URL=redis://:sider@redis:6379
  solade:
    depends_on:
      - redis
      - static
    build: ./solade
    ports:
      - 3000:3000
    env_file: ./solade/.env
    environment:
      - CORS_ORIGINS=http://localhost:3001
      - STATIC_DATA_URL=http://static:3000
      - REDIS_URL=redis://:sider@redis:6379
  solplorer:
    depends_on:
      - solade
    build: ./solplorer
    environment:
      - API_URL=http://solade:3000
    ports:
      - 3001:3000
